Switched deployment docker compose filed to .env files. Added command to Taskfile for generation .env files

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -12,6 +12,7 @@ vars:
   OGEN_VERSION: 'v1.15.1'
   YQ_VERSION: 'v4.45.2'
   MOCKERY_VERSION: 'v2.53.5'
+  ENVSUBST_VERSION: 'v1.4.3'
 
   BIN_DIR: '{{.ROOT_DIR}}/bin'
   GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
@@ -23,6 +24,8 @@ vars:
   PROTOC_GEN_GO: '{{.BIN_DIR}}/protoc-gen-go'
   PROTOC_GEN_GO_GRPC: '{{.BIN_DIR}}/protoc-gen-go-grpc'
   MOCKERY: "{{.BIN_DIR}}/mockery"
+  ENVSUBST: '{{.BIN_DIR}}/envsubst'
+  ENVDIR: '{{.ROOT_DIR}}/deploy/env'
 
   REDOCLY_DOCKER_IMG: 'redocly/cli:2.2.2'
   OPEN_API_ORDER_V1_SPEC_DIR: '{{.ROOT_DIR}}/shared/api/order/v1'
@@ -35,6 +38,7 @@ vars:
   COVERAGE_FILE: total.out
 
   MODULES: assembly inventory order payment platform iam notification
+  SERVICES: core,assembly,inventory,order,payment,iam,notification
 
 tasks:
   install-formatters:
@@ -416,3 +420,38 @@ tasks:
       - task down-order
       - task down-inventory
       - task down-core
+
+  env:install-envsubst:
+    desc: "Installs envsubst into bin/"
+    cmds:
+      - |
+        [ -f {{.ENVSUBST}} ] || {
+          echo "📦 Installing envsubst version {{.ENVSUBST_VERSION}}..."
+          GOBIN={{.BIN_DIR}} go install github.com/a8m/envsubst/cmd/envsubst@{{.ENVSUBST_VERSION}}
+        }
+        echo "✅ envsubst installed: {{.ENVSUBST}}"
+
+  env:generate:
+    desc: "Generates .env files for all services from templates and a common configuration file"
+    deps: [ env:install-envsubst ]
+    cmds:
+      - |
+        ENV_FILE="{{.ENVDIR}}/.env"
+        TEMPLATE_FILE="{{.ENVDIR}}/.env.template"
+        SCRIPT="{{.ENVDIR}}/generate-env.sh"
+        
+        if [ ! -f "$ENV_FILE" ]; then
+          if [ -f "$TEMPLATE_FILE" ]; then
+            echo "🔄 File $ENV_FILE not found, creating from template $TEMPLATE_FILE"
+            cp "$TEMPLATE_FILE" "$ENV_FILE"
+            echo "✅ File $ENV_FILE created. Please check and edit variable values if necessary."
+          else
+            echo "❌ Template $TEMPLATE_FILE not found!"
+            exit 1
+          fi
+        fi
+        
+        chmod +x "$SCRIPT"
+        # Pass the list of services as a comma-separated string
+        export SERVICES="{{.SERVICES}}"
+        ENV_SUBST={{.ENVSUBST}} "$SCRIPT"
